---
- hosts: "all"
  user: "ansible"
  force_handlers: true

  vars_files:
    - "../vars.yml"

  tasks:
    - name: "ensure koala is not running"
      service:
        name: "koala"
        state: "stopped"
      become: true
