---
- hosts: "all"
  user: "ansible"
  force_handlers: true

  vars_files:
    - "../vars.yml"

  tasks:
    - name: "start process of disabling koala's maintenance mode"
      include_tasks: ".koala-maintenance-off.yml"
