---
- hosts: all

  vars_files:
      - "../vars.yml"

  tasks:
    - name: "disable Koala's maintenance mode"
      file:
        state: "absent"
        dest: "/var/www/koala.{{ canonical_hostname }}/MAINTENANCE_MODE"
      become: true
      become_user: "koala"
