---
- hosts: all

  vars_files:
      - ../vars.yml

  tasks:
    - name: "ensure koala is running"
      service:
        name: "koala"
        enabled: true
        state: "started"
      become: true
