---
# TODO install pam_ssh_agent_auth instead of
# setting NOPASSWD.
- name: "enable NOPASSWD for sudo group"
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: "copy deploy keys"
  copy:
    src: "files/{{ item }}"
    dest: "/{{ item }}"
    owner: ansible
    group: ansible
    mode: 0600
  with_items:
    - home/ansible/.ssh/deploy_ed25519
    - home/ansible/.ssh/deploy_ed25519.pub
