---
- name: "enable NOPASSWD for sudo group"
  lineinfile:
    dest: "/etc/sudoers.d/ansible"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    state: "present"
    create: true
    validate: "visudo -cf %s"

- name: "copy deploy keys"
  template:
    src: "templates/{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "ansible"
    group: "ansible"
    mode: "0600"
  with_items:
    - "home/ansible/.ssh/deploy_ed25519"
    - "home/ansible/.ssh/deploy_ed25519.pub"

- name: "disable root login and password authentication over ssh"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "present"
  with_items:
    - { regexp: "^PermitRootLogin ", line: "PermitRootLogin no" }
    - { regexp: "^PasswordAuthentication ", line: "PasswordAuthentication no" }
  notify: "reboot server"

- name: "remove public keys for root account"
  file:
    path: "/root/.ssh/authorized_keys"
    state: "absent"

