---
# TODO install pam_ssh_agent_auth instead of
# setting NOPASSWD.
- name: "enable NOPASSWD for sudo group"
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"
