---
- name: "ensure ipv6 firewalling is enabled"
  lineinfile:
    dest: "/etc/default/ufw"
    regexp: "^IPV6="
    line: "IPV6=yes"
    state: "present"

- name: "allow incoming traffic on specified ports"
  ufw:
    rule: "allow"
    to_port: "{{ item }}"
  with_items:
    - "ssh"
    - "http"
    - "https"

- name: "allow outgoing traffic"
  ufw:
    policy: "allow"
    direction: "outgoing"
    state: "enabled"

- name: "block all other incoming traffic"
  ufw:
    policy: "deny"
    direction: "incoming"
    state: "enabled"

# Remove firewall rule which was implemented because fail2ban didn't support 
# ipv6 at the time. Since 0.10, it does.
- name: "rate limit ipv6 traffic to ssh" 
  ufw:
    rule: "limit"
    from_ip: "::/0"
    to_port: "ssh"
    proto: "tcp"
    delete: true
