---
- name: "install letsencrypt"
  apt:
    name: letsencrypt
    state: present

- name: "create certbot user"
  user:
    name: certbot
    comment: "LetsEncrypt certificate fetcher"
    system: yes
    createhome: no
    shell: /bin/nologin

- name: "create acme-challenges directory"
  file:
    path: /var/www/acme-challenges
    state: directory
    owner: certbot
    group: www-data
    # The 2xxx octal means the group setuid bit is set, meaning
    # all files that get created in this directory will have
    # the group `www-data`
    mode: 2750

- name: "create SSL cert request script"
  template:
    src: "ssl-request.sh.j2"
    dest: "/ssl-request.sh"
