---
- name: "remove help text from motd"
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: "absent"
  with_items:
    - "10-help-text"
    - "51-cloudguest"

- name: "install toilet"
  apt:
    pkg: "toilet"
    state: "present"

- name: "copy motd templates"
  template:
    src: "templates/etc/update-motd.d/{{ item }}.j2"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: "0755"
  with_items:
    - "01-sadserver-header"
    - "02-playbook-revision"

- name: "set custom hostname, in production"
  hostname:
    name: "{{ server_hostname }}"
  when: staging != 'true'

- name: "update hostname in /etc/hosts, in production"
  lineinfile:
    regexp: "^127.0.1.1"
    line:
      "127.0.1.1 {{ server_hostname }}.{{ canonical_hostname }}
      {{ server_hostname }}"
    path: "/etc/hosts"
    state: "present"
  when: staging != 'true'
