---
- name: "install nginx, php-fpm and openssl"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - php-fpm
    - openssl

- name: "copy configuration files"
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/nginx/nginx.conf
    - etc/php/7.0/fpm/php.ini
  notify: reload nginx

- name: "create directory for self-signed certs"
  file:
    path: "/etc/letsencrypt/live/{{ item.main_hostname }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ websites }}"

- name: "create self-signed certs for all websites"
  command: >
    openssl req \
      -x509 \
      -newkey rsa:4096 \
      -keyout /etc/letsencrypt/live/{{ item.main_hostname }}/privkey.pem \
      -out /etc/letsencrypt/live/{{ item.main_hostname }}/fullchain.pem \
      -days 10 \
      -nodes \
      -subj '/C=US/ST=Oregon/L=Portland/O=Sticky/OU=Org/CN=*'
  args:
    creates: "/etc/letsencrypt/live/{{ item.main_hostname }}/privkey.pem"
  with_items: "{{ websites }}"

- name: "copy dhparams and default configuration"
  copy:
    src: "files/{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
  with_items:
    - etc/nginx/dhparams.pem
    - etc/nginx/sites-available/default

- name: "start and enable nginx"
  service:
    name: nginx
    enabled: yes

- name: "create website directories"
  file:
    path: "/var/www/{{ item.user }}/{{ item.main_hostname }}"
    owner: "{{ item.user }}"
    group: www-data
    mode: 0755
    state: directory
  with_items: "{{ websites }}"

- name: "copy website nginx configuraitons"
  template:
    src: "etc/nginx/sites-available/website.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.main_hostname }}.conf"
  with_items: "{{ websites }}"

- name: "enable website nginx configurations"
  file:
    src: "/etc/nginx/sites-available/{{ item.main_hostname }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.main_hostname }}.conf"
    state: link
  with_items: "{{ websites }}"
  notify: reload nginx
