---
# Needed because of Ansible issue #25414
- name: "check if unattended-upgrades is not in progress"
  shell:
    "while fuser /var/lib/dpkg/lock; do sleep 1; done;"
  become: true
  changed_when: false

- name: "install common utilities"
  apt:
    pkg: "{{ item }}"
    state: "present"
  with_items:
    - "aptitude"
    - "htop"
    - "unattended-upgrades"
    - "haveged"

- name: "update all packages"
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 100

- name: "configure unattended-upgrades"
  template:
    src: "templates/{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - "etc/apt/apt.conf.d/50unattended-upgrades"
    - "etc/systemd/system/unattended-upgrades-output.service"
    - "etc/systemd/system/unattended-upgrades-output.timer"
  notify:
    - "systemctl daemon-reload"

- name: "enable unattended-upgrades notification in production"
  service:
    name: "unattended-upgrades-output.timer"
    enabled: "{% if staging == 'true' %}false{% else %}true{% endif %}"
    state: "{% if staging == 'true' %}stopped{% else %}started{% endif %}"

- name: "install slacktee"
  get_url:
    url:
      "https://raw.githubusercontent.com/course-hero/slacktee/{{
      slacktee.revision }}/slacktee.sh"
    dest: "/usr/local/bin/slacktee"
    mode: "0755"
    checksum: "{{ slacktee.checksum }}"

- name: "configure slacktee"
  template:
    src: "templates/{{ item }}"
    dest: "/{{ item }}"
  with_items:
    - "etc/slacktee.conf"
