---
# Contains tasks needed to set up Redis
- block:
  - name: "ensure Redis server and client are present"
    apt:
        name: "{{ item }}"
        state: "present"
    with_items:
        - "redis-server"
        - "redis-tools"
    tags:
        - "packages"

  - name: "ensure Redis server is running and enabled"
    service:
        name: "redis-server"
        enabled: true
        state: "started"
    tags:
        - "service"

  - name: "place Redis config file"
    template:
      src: "templates/{{ path }}.j2"
      dest: "/{{ path }}"
      owner: "redis"
      group: "redis"
      mode: "0640"
    vars:
      path: "etc/redis/redis.conf"
    notify:
      - "restart redis"
