---
- name: "install unattended-upgrades"
  apt:
    pkg: unattended-upgrades
    state: present

- name: "configure unattended-upgrades"
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/apt/apt.conf.d/50unattended-upgrades
