---
- name: "install unattended-upgrades"
  apt:
    pkg: unattended-upgrades
    state: present

- name: "configure unattended-upgrades"
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item | regex_replace('_', '/') }}"
  with_items:
    - etc_apt_apt.conf.d_50unattended-upgrades
