---
- name: "create committee group"
  group:
    name: "committee"
    state: "present"

- name: "create /var/www"
  file:
    path: "/var/www"
    state: "directory"

- name: "create users"
  user:
    name: "{{ item.name }}"
    groups: "{%if item.admin %}sudo,adm{% else %}committee{% endif %}"
    state: "{{ item.state }}"
    home: "{{ item.home_prefix }}/{{ item.name }}"
    move_home: true
  with_items:
    - "{{ users }}"

- name: "fix permissions for chroot of committee users"
  file:
    path: "/var/www/{{ item.name }}"
    owner: "root"
    state: "directory"
  when:
    # List is evaluated as logical AND
    - item.admin != true
    - item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "set shell for admins"
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    state: "{{ item.state }}"
  when:
    # List is evaluated as logical AND
    - item.admin == true
    - item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "add environment to bash prompt"
  lineinfile:
    dest: "/home/{{ item.name }}/.bashrc"
    regexp: "^export PS1="
    line: "export PS1='\\n\\e[31m\\e[1m{% if staging == 'true' %}STAGING{% else %}!! PRODUCTION !!{% endif %}\\e[0m \\e[33m\\e[1m`whoami`@`hostname --long`\\e[0m:`pwd`\\n$ '"
  when: item.admin == true and item.state == 'present'
  with_items:
    - "{{ users }}"
