---
- name: "create committee group"
  group:
    name: "committee"
    state: "present"

- name: "create /var/www"
  file:
    path: "/var/www"
    state: "directory"

- name: "create users"
  user:
    name: "{{ item.name }}"
    groups: "{%if item.admin %}sudo,adm{% else %}committee{% endif %}"
    state: "{{ item.state }}"
  with_items:
    - "{{ users }}"

- name: "set shell for admins"
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    state: "{{ item.state }}"
  when: item.admin == true
  with_items:
    - "{{ users }}"

- name: "move committee users"
  user:
    name: "{{ item.name }}"
    home: "/var/www/{{ item.name }}"
    move_home: true
  when: item.admin != true and item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "fix permissions for chroot of committee users"
  file:
    path: "/var/www/{{ item.name }}"
    owner: "root"
    state: "directory"
  when: item.admin != true and item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "set users' keys"
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.path }}"
    state: "{{ item.0.state }}"
  when: item.0.state == 'present' and item.1.state == 'present'
  with_subelements:
    - "{{ users }}"
    - "keys"

- name: "remove disabled keys from users"
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.path }}"
    state: "absent"
  when: item.0.state == 'present' and item.1.state == 'absent'
  with_subelements:
    - "{{ users }}"
    - "keys"

- name: "add ssh keys of admin users to ansible user"
  authorized_key:
    user: "ansible"
    key: "{{ item.1.path }}"
    state: "{{ item.0.state }}"
  when: item.0.admin == true and item.0.state == 'present' and item.1.state == 'present'
  with_subelements:
    - "{{ users }}"
    - "keys"

- name: "remove disabled keys of admin users from ansible user"
  authorized_key:
    user: "ansible"
    key: "{{ item.1.path }}"
    state: "absent"
  when: item.0.admin == true and item.0.state == 'present' and item.1.state == 'absent'
  with_subelements:
    - "{{ users }}"
    - "keys"
