---
- name: "create committee group"
  group:
    name: "committee"
    state: "present"

- name: "create /var/www"
  file:
    path: "/var/www"
    state: "directory"

- name: "create users"
  user:
    name: "{{ item.name }}"
    groups: "{%if item.admin %}sudo,adm{% else %}committee{% endif %}"
    state: "{{ item.state }}"
  with_items:
    - "{{ users }}"

- name: "set shell for admins"
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    state: "{{ item.state }}"
  when: item.admin == true
  with_items:
    - "{{ users }}"

- name: "move committee users"
  user:
    name: "{{ item.name }}"
    home: "/var/www/{{ item.name }}"
    move_home: true
  when: item.admin != true and item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "fix permissions for chroot of committee users"
  file:
    path: "/var/www/{{ item.name }}"
    owner: "root"
    state: "directory"
  when: item.admin != true and item.state == 'present'
  with_items:
    - "{{ users }}"

- name: "ensure SSH keys for all users are present"
  blockinfile:
    path: "/home/{{ item.0.name }}/.ssh/authorized_keys"
    block: "{{ lookup('file', 'credentials/ssh/' + item.1.id) }}"
    state: item.0.state == 'present' and item.1.state == 'present'
    marker:  "# {mark} SSH key for {{ item.1.id }}"
  with_subelements:
    - "{{ users }}"
    - "keys"
