---
- name: "create committee group"
  group:
    name: committee
    state: present

- name: "create users"
  user:
    name: "{{ item.name }}"
    home: "/var/www/{{ item.name}}"
    move_home: yes # the docs for user_module sucks. Moves existing home dir
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ users }}"

- name: "fix permissions for chroot"
  file:
    path: "/var/www/{{ item.name }}"
    owner: root
    state: directory
  when: "{{ item.groups == 'committee' and item.state == 'present' }}"
  with_items:
    - "{{ users }}"

- name: "set users keys"
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: "{{ item.0.state }}"
  when: "{{ item.0.state == 'present' }}"
  with_subelements:
    - "{{ users }}"
    - keys

