---
- hosts: development
  user: root

  tasks:
    - include: tasks/auth.yml
    - include: tasks/users.yml admins={{ admin_users }}
    - include: tasks/upgrades.yml
    - include: tasks/nginx.yml

  handlers:
    - include: handlers/nginx.yml

  vars:
    security_upgrades: True
    all_upgrades: False

    admin_users:
      laurens:
        github: duijf
      tom:
        github: tomwassenberg
      arian:
        github: arianvp
      martijn:
        github: martijncasteel

...
