---
canonical_hostname: dev.svsticky.nl

users:
  - name: arian
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/arianvp.keys
  - name: laurens
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/duijf.keys
  - name: tom
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/tomwassenberg.keys
  - name: maarten
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/spasticVerbalizer.keys
  - name: yorick
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/yorickvanzweeden.keys

  - name: commit
    groups: committee
    shell: /bin/false
    state: present
    keys:
      - https://github.com/cfda.keys
      - https://github.com/DatDutchDude.keys
      - https://github.com/emielvanrijn.keys
      - https://github.com/GlennStewart125.keys
      - https://github.com/M8eld.keys
      - https://github.com/spasticVerbalizer.keys
      - https://github.com/yorickvanzweeden.keys

  - name: studiereis
    groups: committee
    shell: /bin/false
    state: present
    keys: []

  - name: wintersport
    groups: committee
    shell: /bin/false
    state: present
    keys: []

unattended_upgrades:
  security: True
  all: False

fail2ban:
  loglevel: 3
  ignoreip: 127.0.0.1/8
  bantime: 600
  maxretry: 3

  destemail: root@localhost
  mta: sendmail
  banaction: iptables-multiport

  services:
    - name: sshd
      port: ssh
      filter: sshd
      logpath: /var/log/auth.log

# the upload limit for php-fpm and nginx in megabytes
upload_limit: 15

websites:
  - main_hostname: radio.{{ canonical_hostname }}
    user: commit
    alternative_hostnames: []

  - main_hostname: studytrip.{{ canonical_hostname }}
    user: studiereis
    alternative_hostnames:
      - studiereis.{{ canonical_hostname }}

  - main_hostname: wintersport.{{ canonical_hostname }}
    user: wintersport
    alternative_hostnames: []

  - main_hostname: koala.{{ canonical_hostname }}
    custom_config: true
    alternative_hostnames:
      - intro.{{ canonical_hostname }}

  - main_hostname: metrics.{{ canonical_hostname }}
    custom_config: true
    alternative_hostnames:
      - status.{{ canonical_hostname }}

# koala configuration
ssl_certificate: /etc/letsencrypt/live/koala.{{ canonical_hostname }}/fullchain.pem
ssl_certificate_key: /etc/letsencrypt/live/koala.{{ canonical_hostname }}/privkey.pem
koala:
  environment: production
  server: unicorn # or webrick
  git_ref: ansible_test # Should be master, when in production
  ruby_version: 2.3.0
