---
canonical_hostname: "dev.svsticky.nl"

users:
  - name: "arian"
    admin: true
    state: "present"
    keys:
      - key: "arianvp.github.pub"
        state: "present"

  - name: "laurens"
    admin: true
    state: "present"
    keys:
      - key: "duijf.github.pub"
        state: "present"

  - name: "maarten"
    admin: true
    state: "present"
    keys:
      - key: "spasticVerbalizer.github.pub"
        state: "present"

  - name: "tom"
    admin: true
    state: "present"
    keys:
      - key: "tomassenberg.github.pub"
        state: "present"

  - name: "yorick"
    admin: true
    state: "present"
    keys:
      - key: "yorick.github.pub"
        state: "present"

  - name: "bestuur"
    admin: false
    state: "present"
    keys:
      - key: "PabloEnriqueIglesias.github.pub"
        state: "present"
      - key: "Sithias.github.pub"
        state: "present"
      - key: "yorickvanzweeden.github.pub"
        state: "present"
      - key: "RobinSikkens.github.pub"
        state: "present"

  - name: "commit"
    admin: false
    state: "present"
    keys:
      - key: "cdfa.github.pub"
        state: "present"
      - key: "DatDutchDude.github.pub"
        state: "present"
      - key: "emielvanrijn.github.pub"
        state: "present"
      - key: "GlennStewart125.github.pub"
        state: "present"
      - key: "M8eld.github.pub"
        state: "present"
      - key: "spasticVerbalizer.github.pub"
        state: "present"
      - key: "yorickvanzweeden.github.pub"
        state: "present"

  - name: "dgdarc"
    admin: false
    state: "present"
    keys: []

  - name: "indievelopment"
    admin: false
    state: "present"
    keys:
      - key: "geert.manual.pub"
        state: "present"
      - key: "marc.manual.pub"
        state: "present"

  - name: "sodi"
    admin: false
    state: "present"
    keys:
      - key: "emielvanrijn.github.pub"
        state: "present"
      - key: "rcdewit.github.pub"
        state: "present"
      - key: "yorickvanzweeden.github.pub"
        state: "present"

  - name: "stichting"
    admin: false
    state: "present"
    keys: []

  - name: "studytrip"
    admin: false
    state: "present"
    keys:
      - key: "rcdewit.github.pub"
        state: "present"
      - key: "yorickvanzweeden.github.pub"
        state: "present"

  - name: "symposium"
    admin: false
    state: "present"
    keys:
      - key: "DatDutchDude.github.pub"
        state: "present"
      - key: "emielvanrijn.github.pub"
        state: "present"

  - name: "wintersport"
    admin: false
    state: "present"
    keys: []

unattended_upgrades:
  security: true
  all: false

fail2ban:
  loglevel: "WARNING"
  ignoreip: "127.0.0.1/8"
  bantime: 600
  maxretry: 3
  banaction: "iptables-multiport"

  services:
    - name: "sshd"
      port: "ssh"
      filter: "sshd"
      logpath: "/var/log/auth.log"

# the upload limit for php-fpm and nginx in megabytes
upload_limit: 15

# Defines the default of requesting staging certificates, or not.
# Can be disabled on a per-website basis by adding `real_certificate`
staging_certificates: true

websites:
# Domains that are commented are done so
# because of DNS, uncomment when in production

# - name: "dgdarc.nl"
#   user: "dgdarc"
#   database: true
#   alternative_names:
#     - "www.dgdarc.nl"
#     - "dgdarc.com"
#     - "www.dgdarc.com"

# - name: "indievelopment.nl"
#   user: "indievelopment"
#   database: true
#   alternative_names:
#     - "www.indievelopment.nl"
#     - "indiedevelopment.nl"
#     - "www.indiedevelopment.nl"

  - name: "digidecs.{{ canonical_hostname }}"
    user: "commit"
    alternative_names: []

  - name: "koala.{{ canonical_hostname }}"
    custom_config: true
    alternative_names:
      - "intro.{{ canonical_hostname }}"
      - "leden.{{ canonical_hostname }}"
      - "members.{{ canonical_hostname }}"

  - name: "metrics.{{ canonical_hostname }}"
    custom_config: true
    alternative_names:
      - "status.{{ canonical_hostname }}"

  - name: "phpmyadmin.{{ canonical_hostname }}"
    custom_config: true
    database: "phpmyadmin"
    alternative_names:
      - "pma.{{ canonical_hostname }}"

  - name: "radio.{{ canonical_hostname }}"
    user: "commit"
    alternative_names: []

# - name: "savadaba.nl"
#   custom_config: true
#   alternative_names:
#     - "www.savadaba.nl"

# - name: "sodi.nl"
#   user: "sodi"
#   database: "sodi"
#   alternative_names:
#     - "www.sodi.nl"

# - name: "stichtingsticky.nl"
#   user: "stichting"
#   alternative_names:
#     - "www.stichtingsticky.nl"

  - name: "studytrip.{{ canonical_hostname }}"
    user: "studytrip"
    database: "studytrip"
    alternative_names:
      - "studiereis.{{ canonical_hostname }}"

  - name: "{{ canonical_hostname }}"
    user: "commit"
    database: "svsticky"
    custom_config: true
    alternative_names:
      - "www.{{ canonical_hostname }}"
#     - "stickyutrecht.nl"
#     - "www.stickyutrecht.nl"
#     - "studieverenigingsticky.nl"
#     - "www.studieverenigingsticky.nl"

  - name: "symposium.{{ canonical_hostname }}"
    user: "symposium"
    database: "symposium"
    alternative_names: []

  - name: "wintersport.{{ canonical_hostname }}"
    user: "wintersport"
    alternative_names: []

koala:
  environment: "production"
  server: "unicorn" # or webrick
  git_ref: "development" # Should be master, when in production
  ruby_version: "2.3.0"

slacktee:
  revision: "2dd488b93fa13d305d27c1c820641e600845710e"
  checksum: "sha256:b59522b40de167e5c88ddf09f5d02560759902fc503e0bd3cea5c1fa45b780df"
