---
canonical_hostname: dev.svsticky.nl

users:
  - name: arian
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/arianvp.keys
  - name: laurens
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/duijf.keys
  - name: tom
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/tomwassenberg.keys
  - name: maarten
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/spasticVerbalizer.keys
  - name: yorick
    groups: sudo,adm
    shell: /bin/bash
    state: present
    keys:
      - https://github.com/yorickvanzweeden.keys

  - name: bestuur
    groups: committee
    shell: /bin/false
    state: present
    keys: []
  - name: commit
    groups: committee
    shell: /bin/false
    state: present
    keys:
      - https://github.com/cdfa.keys
      - https://github.com/DatDutchDude.keys
      - https://github.com/emielvanrijn.keys
      - https://github.com/GlennStewart125.keys
      - https://github.com/M8eld.keys
      - https://github.com/spasticVerbalizer.keys
      - https://github.com/yorickvanzweeden.keys
  - name: dgdarc
    groups: committee
    shell: /bin/false
    state: present
    keys: []
  - name: indievelopment
    groups: committee
    shell: /bin/false
    state: present
    keys: []
  - name: sodi
    groups: committee
    shell: /bin/false
    state: present
    keys:
      - https://github.com/emielvanrijn.keys
      - https://github.com/rcdewit.keys
      - https://github.com/yorickvanzweeden.keys
  - name: stichting
    groups: committee
    shell: /bin/false
    state: present
    keys: []
  - name: studiereis
    groups: committee
    shell: /bin/false
    state: present
    keys:
      - https://github.com/rcdewit.keys
      - https://github.com/yorickvanzweeden.keys
  - name: symposium
    groups: committee
    shell: /bin/false
    state: present
    keys:
      - https://github.com/DatDutchDude.keys
      - https://github.com/emielvanrijn.keys
  - name: wintersport
    groups: committee
    shell: /bin/false
    state: present
    keys: []

unattended_upgrades:
  security: True
  all: False

fail2ban:
  loglevel: 3
  ignoreip: 127.0.0.1/8
  bantime: 600
  maxretry: 3

  destemail: root@localhost
  mta: sendmail
  banaction: iptables-multiport

  services:
    - name: sshd
      port: ssh
      filter: sshd
      logpath: /var/log/auth.log

# the upload limit for php-fpm and nginx in megabytes
upload_limit: 15

websites:
# Commented because of DNS, uncomment when in production
#  - name: "dgdarc.nl"
#    user: "dgdarc"
#    database: true
#    alternative_names:
#      - "dgdarc.com"

  - name: "koala.{{ canonical_hostname }}"
    custom_config: true
    alternative_names:
      - "intro.{{ canonical_hostname }}"
      - "leden.{{ canonical_hostname }}"
      - "members.{{ canonical_hostname }}"

  - name: "metrics.{{ canonical_hostname }}"
    custom_config: true
    alternative_names:
      - "status.{{ canonical_hostname }}"

  - name: "studytrip.{{ canonical_hostname }}"
    user: "laurens"
    database: true
    alternative_names:
      - "studiereis.{{ canonical_hostname }}"

# koala configuration
ssl_certificate: /etc/letsencrypt/live/koala.{{ canonical_hostname }}/fullchain.pem
ssl_certificate_key: /etc/letsencrypt/live/koala.{{ canonical_hostname }}/privkey.pem
koala:
  environment: production
  server: unicorn # or webrick
  git_ref: feature/digital-enrollments # Should be master, when in production
  ruby_version: 2.3.0

slacktee:
  revision: 2dd488b93fa13d305d27c1c820641e600845710e
  checksum: sha256:b59522b40de167e5c88ddf09f5d02560759902fc503e0bd3cea5c1fa45b780df
  webhook_url: https://hooks.slack.com/services/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
